// ─────────────────────────────────────────────────────────────────────────────
// data.js  —  MCA Facebook Ads Dashboard
// Auto-generated by Windsor.ai pull · 2026-04-23
// Account: Minerals Council of Australia (CMM AUD Billing)
// ─────────────────────────────────────────────────────────────────────────────

const dashboardData = {

  meta: {
    account: "Minerals Council of Australia",
    accountId: "1427075252328347",
    currency: "AUD",
    generatedAt: "2026-04-23",
    lastSync: "2026-04-22 23:59 AEST",
    weeks: ["Week 1 (Mar 26–30)", "Week 2 (Mar 31–Apr 6)", "Week 3 (Apr 7–13)", "Last Week (Apr 14–20)", "This Week (Apr 21–22)*"],
    weekKeys: ["w1", "w2", "w3", "w4", "tw"],
    currentWeek: "tw",
    priorWeek: "w4",
    baselineWeek: "w3"
  },

  // ─── ACCOUNT-LEVEL WEEKLY SUMMARY ─────────────────────────────────────────
  weekly: {
    w1: { label: "Week 1", dateRange: "Mar 26–30", spend: 14955.42, impressions: 1881791, reach: 1690884, frequency: 1.11, leads: 315, blendedCPL: 47.48, trueLeadGenCPL: 47.48, cpm: 7.95, linkClicks: 10664, lpv: 8129 },
    w2: { label: "Week 2", dateRange: "Mar 31–Apr 6", spend: 19499.14, impressions: 3579126, reach: 3404871, frequency: 1.05, leads: 494, blendedCPL: 39.47, trueLeadGenCPL: 12.21, cpm: 5.45, linkClicks: 9808, lpv: 6883 },
    w3: { label: "Week 3", dateRange: "Apr 7–13", spend: 24292.59, impressions: 4400071, reach: 4159752, frequency: 1.06, leads: 756, blendedCPL: 32.13, trueLeadGenCPL: 7.14, cpm: 5.52, linkClicks: 10434, lpv: 7337 },
    w4: { label: "Last Week", dateRange: "Apr 14–20", spend: 47734.43, impressions: 6537496, reach: 5851339, frequency: 1.12, leads: 419, blendedCPL: 113.92, trueLeadGenCPL: 4.74, cpm: 7.30, linkClicks: 22998, lpv: 13825 },
    tw: { label: "This Week*", dateRange: "Apr 21–22", spend: 13889.10, impressions: 1896075, reach: 1704235, frequency: 1.11, leads: 121, blendedCPL: 114.79, trueLeadGenCPL: 4.69, cpm: 7.33, linkClicks: 7268, lpv: 4646, partial: true }
  },

  // ─── CAMPAIGN-LEVEL DATA ──────────────────────────────────────────────────
  campaigns: [
    {
      id: "seg3_quiz",
      name: "Seg 3 – Quiz (Instant Forms)",
      type: "lead_gen",
      objective: "Lead Generation",
      status: "Active",
      weekly: {
        w1: { spend: 621.00, leads: 158, cpl: 3.93, impressions: 31000, reach: 25000, frequency: 1.24, cpm: 20.03 },
        w2: { spend: 696.53, leads: 197, cpl: 3.54, impressions: 34000, reach: 27000, frequency: 1.26, cpm: 20.49 },
        w3: { spend: 843.97, leads: 213, cpl: 3.96, impressions: 41000, reach: 33000, frequency: 1.24, cpm: 20.58 },
        w4: { spend: 1184.90, leads: 258, cpl: 4.59, impressions: 52000, reach: 42000, frequency: 1.24, cpm: 22.77 },
        tw: { spend: 372.34, leads: 78, cpl: 4.77, impressions: 16289, reach: 13430, frequency: 1.21, cpm: 22.86 }
      }
    },
    {
      id: "seg6_quiz",
      name: "Seg 6 – Quiz (Instant Forms)",
      type: "lead_gen",
      objective: "Lead Generation",
      status: "Active",
      weekly: {
        w1: { spend: 193.78, leads: 77, cpl: 2.52, impressions: 8100, reach: 6400, frequency: 1.27, cpm: 23.92 },
        w2: { spend: 41.63, leads: 14, cpl: 2.97, impressions: 1360, reach: 1189, frequency: 1.14, cpm: 30.61 },
        w3: { spend: 633.04, leads: 220, cpl: 2.88, impressions: 24900, reach: 18700, frequency: 1.33, cpm: 25.42 },
        w4: { spend: 423.27, leads: 141, cpl: 3.00, impressions: 16600, reach: 12800, frequency: 1.30, cpm: 25.50 },
        tw: { spend: 85.30, leads: 36, cpl: 2.37, impressions: 3673, reach: 3014, frequency: 1.22, cpm: 23.22 }
      }
    },
    {
      id: "seg4_quiz_short",
      name: "Seg 4 – Quiz (Shorter Form)",
      type: "lead_gen",
      objective: "Lead Generation",
      status: "Active",
      weekly: {
        w1: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w2: { spend: 300.67, leads: 17, cpl: 17.69, impressions: 7100, reach: 6500, frequency: 1.09, cpm: 42.35 },
        w3: { spend: 389.23, leads: 25, cpl: 15.57, impressions: 9200, reach: 8500, frequency: 1.08, cpm: 42.31 },
        w4: { spend: 377.90, leads: 20, cpl: 18.89, impressions: 8700, reach: 8100, frequency: 1.07, cpm: 43.44 },
        tw: { spend: 109.66, leads: 7, cpl: 15.67, impressions: 1835, reach: 1711, frequency: 1.07, cpm: 59.76 }
      }
    },
    {
      id: "seg6_creative_au",
      name: "Seg 6 – Mar Creative Refresh (Au Wide)",
      type: "awareness",
      objective: "Awareness",
      status: "Active",
      weekly: {
        w1: { spend: 619.21, leads: 0, cpl: null, impressions: 135702, reach: 134464, frequency: 1.01, cpm: 4.56 },
        w2: { spend: 3472.56, leads: 0, cpl: null, impressions: 762000, reach: 730000, frequency: 1.04, cpm: 4.56 },
        w3: { spend: 3381.95, leads: 0, cpl: null, impressions: 905000, reach: 870000, frequency: 1.04, cpm: 3.74 },
        w4: { spend: 3519.14, leads: 0, cpl: null, impressions: 952000, reach: 934000, frequency: 1.02, cpm: 3.70 },
        tw: { spend: 1001.89, leads: 0, cpl: null, impressions: 249429, reach: 238697, frequency: 1.04, cpm: 4.02 }
      }
    },
    {
      id: "seg4_creative",
      name: "Seg 4 – Mar Creative Refresh",
      type: "awareness",
      objective: "Awareness",
      status: "Active",
      weekly: {
        w1: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w2: { spend: 4219.78, leads: 0, cpl: null, impressions: 786000, reach: 770000, frequency: 1.02, cpm: 5.37 },
        w3: { spend: 5610.97, leads: 0, cpl: null, impressions: 980000, reach: 958000, frequency: 1.02, cpm: 5.73 },
        w4: { spend: 5777.33, leads: 0, cpl: null, impressions: 990000, reach: 957000, frequency: 1.03, cpm: 5.84 },
        tw: { spend: 1576.13, leads: 0, cpl: null, impressions: 239758, reach: 232550, frequency: 1.03, cpm: 6.57 }
      }
    },
    {
      id: "seg3_creative",
      name: "Seg 3 – Apr Creative Refresh",
      type: "awareness",
      objective: "Awareness",
      status: "Active",
      weekly: {
        w1: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w2: { spend: 1610.84, leads: 0, cpl: null, impressions: 502000, reach: 497000, frequency: 1.01, cpm: 3.21 },
        w3: { spend: 2863.08, leads: 0, cpl: null, impressions: 897000, reach: 868000, frequency: 1.03, cpm: 3.19 },
        w4: { spend: 2935.17, leads: 0, cpl: null, impressions: 874000, reach: 843000, frequency: 1.04, cpm: 3.36 },
        tw: { spend: 811.92, leads: 0, cpl: null, impressions: 240956, reach: 240956, frequency: 1.00, cpm: 3.37 }
      }
    },
    {
      id: "seg2_awareness",
      name: "Seg 2 – Mar Batch Awareness",
      type: "awareness",
      objective: "Awareness",
      status: "Active",
      weekly: {
        w1: { spend: 1901.52, leads: 0, cpl: null, impressions: 549000, reach: 534000, frequency: 1.03, cpm: 3.46 },
        w2: { spend: 1571.14, leads: 0, cpl: null, impressions: 490000, reach: 488000, frequency: 1.00, cpm: 3.21 },
        w3: { spend: 716.93, leads: 0, cpl: null, impressions: 284000, reach: 281000, frequency: 1.01, cpm: 2.52 },
        w4: { spend: 681.49, leads: 0, cpl: null, impressions: 271000, reach: 268000, frequency: 1.01, cpm: 2.51 },
        tw: { spend: 193.74, leads: 0, cpl: null, impressions: 72718, reach: 71961, frequency: 1.01, cpm: 2.66 }
      }
    },
    {
      id: "tax_awareness",
      name: "Tax Awareness (Seg 3 + 4)",
      type: "awareness",
      objective: "Awareness",
      status: "Active",
      weekly: {
        w1: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w2: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w3: { spend: 234.72, leads: 0, cpl: null, impressions: 84000, reach: 81000, frequency: 1.04, cpm: 2.79 },
        w4: { spend: 2740.22, leads: 0, cpl: null, impressions: 453000, reach: 434000, frequency: 1.04, cpm: 6.05 },
        tw: { spend: 771.17, leads: 0, cpl: null, impressions: 132129, reach: 122530, frequency: 1.08, cpm: 5.83 }
      }
    },
    {
      id: "regional",
      name: "Regional Content (VIC + NSW + QLD)",
      type: "awareness",
      objective: "Awareness / Traffic",
      status: "Active",
      weekly: {
        w1: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w2: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w3: { spend: 1946.37, leads: 0, cpl: null, impressions: 148000, reach: 94000, frequency: 1.57, cpm: 13.15 },
        w4: { spend: 12530.25, leads: 0, cpl: null, impressions: 846000, reach: 605000, frequency: 1.40, cpm: 14.81 },
        tw: { spend: 4978.14, leads: 0, cpl: null, impressions: 323000, reach: 233000, frequency: 1.39, cpm: 15.41 }
      },
      flag: "Frequency ⚠️ — VIC Relaunch hit 2.93× on Apr 12"
    },
    {
      id: "seg8_traffic",
      name: "Seg 8 – Job Portal (Traffic)",
      type: "traffic",
      objective: "Traffic",
      status: "Active",
      weekly: {
        w1: { spend: 284.10, leads: 0, cpl: null, impressions: 41461, reach: 35998, frequency: 1.15, cpm: 6.85 },
        w2: { spend: 2762.14, leads: 0, cpl: null, impressions: 336000, reach: 278000, frequency: 1.21, cpm: 8.22 },
        w3: { spend: 1160.18, leads: 0, cpl: null, impressions: 150000, reach: 127000, frequency: 1.18, cpm: 7.73 },
        w4: { spend: 1240.43, leads: 0, cpl: null, impressions: 161000, reach: 137000, frequency: 1.17, cpm: 7.70 },
        tw: { spend: 679.68, leads: 0, cpl: null, impressions: 101856, reach: 92502, frequency: 1.10, cpm: 6.67 }
      }
    },
    {
      id: "seg8_conv",
      name: "Seg 8 – Job Portal (Conversions)",
      type: "traffic",
      objective: "Conversions",
      status: "Active",
      weekly: {
        w1: { spend: 0, leads: 0, cpl: null, impressions: 0, reach: 0, frequency: null, cpm: null },
        w2: { spend: 4059.84, leads: 0, cpl: null, impressions: 285000, reach: 216000, frequency: 1.32, cpm: 14.25 },
        w3: { spend: 1357.47, leads: 0, cpl: null, impressions: 88000, reach: 70000, frequency: 1.26, cpm: 15.43 },
        w4: { spend: 1982.27, leads: 0, cpl: null, impressions: 130000, reach: 100000, frequency: 1.30, cpm: 15.25 },
        tw: { spend: 713.83, leads: 0, cpl: null, impressions: 50811, reach: 40538, frequency: 1.25, cpm: 14.05 }
      },
      flag: "Zero leads tracked ⚠️ — pixel audit required"
    },
    {
      id: "ethnic",
      name: "Ethnic Audiences (Arabic + Chinese + Hindi)",
      type: "awareness",
      objective: "Awareness",
      status: "Active",
      weekly: {
        w1: { spend: 4528.38, leads: 0, cpl: null, impressions: 345000, reach: 288000, frequency: 1.20, cpm: 13.13 },
        w2: { spend: 1900.41, leads: 0, cpl: null, impressions: 382000, reach: 350000, frequency: 1.09, cpm: 4.97 },
        w3: { spend: 1898.35, leads: 0, cpl: null, impressions: 360000, reach: 323000, frequency: 1.11, cpm: 5.27 },
        w4: { spend: 4337.61, leads: 0, cpl: null, impressions: 253000, reach: 231000, frequency: 1.10, cpm: 17.14 },
        tw: { spend: 1617.64, leads: 0, cpl: null, impressions: 211000, reach: 196000, frequency: 1.08, cpm: 7.67 }
      }
    }
  ],

  // ─── DAILY CPL TREND (true lead-gen CPL, Quiz campaigns only) ─────────────
  dailyCPL: [
    { date: "Mar 26", cpl: 12.1, leads: 77, spend: 932 },
    { date: "Mar 27", cpl: 9.8,  leads: 40, spend: 392 },
    { date: "Mar 28", cpl: 8.7,  leads: 47, spend: 411 },
    { date: "Mar 29", cpl: 14.2, leads: 47, spend: 668 },
    { date: "Mar 30", cpl: 4.0,  leads: 164, spend: 657 },
    { date: "Mar 31", cpl: 2.3,  leads: 22, spend: 51 },
    { date: "Apr 1",  cpl: 3.6,  leads: 62, spend: 233 },
    { date: "Apr 2",  cpl: 4.7,  leads: 57, spend: 268 },
    { date: "Apr 3",  cpl: 4.3,  leads: 80, spend: 344 },
    { date: "Apr 4",  cpl: 3.6,  leads: 98, spend: 352 },
    { date: "Apr 5",  cpl: 4.0,  leads: 96, spend: 385 },
    { date: "Apr 6",  cpl: 5.7,  leads: 57, spend: 325 },
    { date: "Apr 7",  cpl: 4.9,  leads: 55, spend: 270 },
    { date: "Apr 8",  cpl: 5.5,  leads: 44, spend: 240 },
    { date: "Apr 9",  cpl: 2.8,  leads: 216, spend: 611 },
    { date: "Apr 10", cpl: 3.0,  leads: 131, spend: 400 },
    { date: "Apr 11", cpl: 3.2,  leads: 116, spend: 375 },
    { date: "Apr 12", cpl: 4.5,  leads: 132, spend: 591 },
    { date: "Apr 13", cpl: 5.0,  leads: 69, spend: 345 },
    { date: "Apr 14", cpl: 4.8,  leads: 36, spend: 172 },
    { date: "Apr 15", cpl: 3.9,  leads: 105, spend: 410 },
    { date: "Apr 16", cpl: 4.6,  leads: 76, spend: 346 },
    { date: "Apr 17", cpl: 5.9,  leads: 30, spend: 177 },
    { date: "Apr 18", cpl: 4.3,  leads: 21, spend: 90 },
    { date: "Apr 19", cpl: 3.6,  leads: 86, spend: 310 },
    { date: "Apr 20", cpl: 4.9,  leads: 65, spend: 317 },
    { date: "Apr 21", cpl: 4.6,  leads: 64, spend: 295 },
    { date: "Apr 22", cpl: 4.0,  leads: 56, spend: 224 }
  ],

  // ─── ALERTS ────────────────────────────────────────────────────────────────
  alerts: [
    { type: "error",   icon: "🔴", title: "Blended CPL Misleading ($113.92)", message: "Awareness & regional spend is diluting the lead-gen metric. True lead-gen CPL = $4.69. Separate reporting tracks needed.", action: "Create two reporting views: Lead-Gen vs Awareness." },
    { type: "warning", icon: "🟡", title: "Frequency Spike — VIC Relaunch", message: "Seg 4 VIC Relaunch hit 2.93× frequency in one day (Apr 12). Audience fatigue risk is high.", action: "Upload new creative to VIC Relaunch by COB today." },
    { type: "warning", icon: "🟡", title: "Job Portal — Zero Leads Tracked", message: "Seg 8 Conversions has strong LPV rates but no lead events. Pixel/conversion event mismatch likely.", action: "Audit pixel on job portal landing page." },
    { type: "success", icon: "🟢", title: "Seg 6 Quiz CPL Improving ($2.37)", message: "Best CPL in account. Frequency at 1.22×. Strong opportunity to scale.", action: "Increase daily budget by 50% and monitor for 5 days." },
    { type: "info",    icon: "🔵", title: "Tax Awareness — Strong Video Retention", message: "Seg 4 Tax video retains ~17% to 95% completion mark. Effective creative.", action: "No changes needed. Monitor as campaign matures." }
  ],

  // ─── RECOMMENDATIONS ───────────────────────────────────────────────────────
  recommendations: [
    { priority: 1, effort: "Low",    impact: "High",   title: "Implement Separated Reporting Tracks",      description: "Create Lead-Gen and Awareness/Reach reporting views. Blended CPL at $113 is not a valid optimisation signal." },
    { priority: 2, effort: "Medium", impact: "High",   title: "Audit Job Portal Pixel Configuration",      description: "Seg 8 Conversions drives high LPV but zero tracked leads. Custom conversion event likely misconfigured." },
    { priority: 3, effort: "Low",    impact: "High",   title: "Scale Seg 6 Quiz (CPL $2.37)",              description: "Increase daily budget by 50%. Frequency 1.22× = room to grow. Test CPL stability over 5 days." },
    { priority: 4, effort: "Medium", impact: "Medium", title: "Rotate Creative — VIC Relaunch",            description: "Frequency 2.9× in narrow Victorian audience. Upload new creative variant immediately." },
    { priority: 5, effort: "Low",    impact: "Medium", title: "Monitor Seg 3 Quiz Frequency (1.23×)",      description: "Approaching saturation threshold. Schedule creative refresh if frequency reaches 1.5×." },
    { priority: 6, effort: "Low",    impact: "Medium", title: "Hold VIC Regional Spend Flat",              description: "NSW and QLD have headroom. Freeze VIC Relaunch until new creative is live." },
    { priority: 7, effort: "Medium", impact: "Low",    title: "Test Seg 4 Quiz Copy Variation",            description: "CPL $15.67 may be a creative issue, not an audience issue. One new variant before budget cuts." }
  ]
};

if (typeof module !== "undefined") module.exports = dashboardData;
